### ISSUE TITLE
Tab Index

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#153]
Add a new inspector option for setting the tabindex of an element in a form screen. 

https://www.w3schools.com/tags/att_tabindex.asp

**Comment by chipit24** [comment]
@velkymx What would be the main benefit of allowing users to modify form elements' `tabIndex`? Modifying tab index is already an edge case, and allowing users to modify it may just allow them to create an accessibility mess.

From [WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_general_between):
> The default order of elements in the tab sequence is the order of elements in the DOM. The DOM order also determines screen reader reading order. It is important to keep the keyboard tab sequence and the screen reader reading order aligned, logical, and predictable [...]

And from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex):
> Avoid using `tabindex` values greater than 0. Doing so will make it difficult for people who rely on assistive technology to navigate and operate page content.

**Comment by velkymx** [comment]
Will research accessibility
