### ISSUE TITLE
Dynamic Select / Radio / Checkbox groups

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#155]
As a user I want to be able to use my data to populate dropdowns, radio groups and checkbox groups. Adjust the inspector for these controls to use this new UI and functionality in the inspector. NOTE: Collections options will be part of that package.

![image](https://user-images.githubusercontent.com/535300/56756812-7c76a500-6747-11e9-94a4-cfa69a09fb7e.png)

- [x] Select control update
- [x] Radio group control update
- [ ] ~~Checkbox group control update~~

**Comment by velkymx** [comment]
Don't worry about the third collections option

**Comment by velkymx** [comment]
```
{
    "chooseone": "new",
    "patients": [
        {
            "id": 1,
            "name":"Alan"
        },
        {
            "id": 2,
            "name":"Alan"
        },        
    ]
}
```

**Comment by velkymx** [comment]
Updated UI for the Provided JSON data

![image](https://user-images.githubusercontent.com/535300/60113400-89ebe380-9726-11e9-9bbb-0d43cd3f5bac.png)

**Comment by chipit24** [comment]
I created a separate issue for adding the checkbox group control: https://github.com/ProcessMaker/screen-builder/issues/279.
