### ISSUE TITLE
Input Type Icon

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#158]
On the component from, between the drag arrows and the title, show the icon from the control type.

**Comment by tuantruong625** [comment]
@velkymx 
<img width="568" alt="Screen Shot 2019-06-20 at 10 02 59 AM" src="https://user-images.githubusercontent.com/26545455/59855261-ab258c00-9342-11e9-830e-68509a6687b0.png">

What do you think about removing the drag arrow icon and just having the control type icon and the title? I think with all three element the header looks busy. Also when the user hovers over the form element the cursor sets to `move` to indicate the element can be moved.

**Comment by velkymx** [comment]
@tuantruong625 what if we add text-muted to the drag icon?

**Comment by tuantruong625** [comment]
@velkymx 
<img width="568" alt="Screen Shot 2019-06-20 at 10 30 56 AM" src="https://user-images.githubusercontent.com/26545455/59857236-87fcdb80-9346-11e9-981a-365712bd2e9e.png">

with `text-muted`.
