### ISSUE TITLE
"Drag Here" jumps around

### ISSUE THREAD

**Issue by ssshake** [ProcessMaker/screen-builder#170]
You should be able to drag on top of drag here. So change the way we're doing this entirely. Currently drag here is a draggable item itself.

https://www.dropbox.com/s/5l7h7n956ra65r7/drag-here-weirdness.mov?dl=0

**Comment by velkymx** [comment]
This still an open issue. We've removed it for our release, but it should work as spec'd.

**Comment by tuantruong625** [comment]
@velkymx 
What do you think about having the `Drag element here` as a placeholder when the renderer container is empty. @chipit24 and I had some discussion about having the `Drag element here` being always visible does not add anything for the use but only visual noise. Similar for an input field placeholder disappearing once the user types into the field.

**Comment by velkymx** [comment]
The functionality show work just like this: https://www.dropbox.com/s/7af9otkfetu8vf8/draghere-example.mov?dl=0
