### ISSUE TITLE
Placing Rich Text control inside table makes the control disappear

### ISSUE THREAD

**Issue by PMQABen** [ProcessMaker/screen-builder#181]
![image](https://user-images.githubusercontent.com/28575916/57876518-5c785580-77ca-11e9-9411-961e0d67801c.png)

**Comment by chipit24** [comment]
Closing as this no longer appears to be an issue. Here is a video of the rich text input rendering correctly inside of a table in the screen builder: https://www.dropbox.com/s/846c9gs6hym603t/rich_text_in_table.mov?dl=0.
