### ISSUE TITLE
Error Message: The undefined field is required.

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#186]
![Screenshot 2019-05-16 17 17 10](https://user-images.githubusercontent.com/535300/57895059-8a778d00-77fe-11e9-96bb-cacdf89a2eb2.png)

Should say the Name Field is required as it does in the error panel

**Comment by chipit24** [comment]
This is now fixed on latest develop:

<img width="300" alt="Screen Shot 2019-05-24 at 1 10 34 PM" src="https://user-images.githubusercontent.com/7561061/58345026-59621280-7e25-11e9-9d30-eb361926293b.png">
