### ISSUE TITLE
Browse Away + Timeout

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#277]
![image](https://user-images.githubusercontent.com/535300/60538084-c1c2d000-9cbe-11e9-9da4-074440c105f9.png)

**Comment by velkymx** [comment]
Ref: FOUR-160

**Comment by tuantruong625** [comment]
@velkymx Having trouble reproducing this bug. Could it be an older version of screen builder? I noticed the screen builder looks different in the screenshot.

**Comment by tuantruong625** [comment]
Not a bug.
