### ISSUE TITLE
Multicolumn All "X"s

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#289]
I can't tell which element is selected. I'd like to add the frame around the active element.

![image](https://user-images.githubusercontent.com/535300/61065416-71332d00-a3b8-11e9-86a7-d71160a461a6.png)

**Comment by tuantruong625** [comment]
@velkymx 
What do you think about having a slimmer selected state for elements inside a table?

**Selected State with Card Header and Icons**

![selected-state](https://user-images.githubusercontent.com/26545455/61081068-57afd680-a3f4-11e9-96ac-8a0daa852a00.gif)

**Selected State with delete icon and border**

<img width="644" alt="Screen Shot 2019-07-11 at 3 55 15 PM" src="https://user-images.githubusercontent.com/26545455/61081079-5e3e4e00-a3f4-11e9-9e57-ae3036291411.png">

**Comment by velkymx** [comment]
This is a definite improvement over the current setup.

**Comment by tuantruong625** [comment]
Do we want to go with the first screen capture or the slimed down version?
