### ISSUE TITLE
Required Field not Respected

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#299]
The problem arises for controls nested inside of the multi-column table control. Once you drag the control, the required option is ignored.

https://processmaker.slack.com/files/U896R0VLN/FLV7E5R54/required.mp4

**Comment by velkymx** [comment]
https://www.dropbox.com/s/3aney0zc1wg0fym/visibility%20rules%20share%20values.mp4?dl=0

**Comment by chipit24** [comment]
@velkymx Can't reproduce this bug. It's working as expected on the latest `develop` branch. From the video it looks like an older version of screen builder is being used.
