### ISSUE TITLE
Screen Builder Inspector Configs

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#300]
Attached is the master list of controls and their inspector configuration. The screen builder needs to be updated to match.

https://docs.google.com/document/d/1xLekCTfdXJ8H_qlGs1mmEVO2UjRXIY-x73csCytDzsA/edit?usp=sharing

**Comment by chipit24** [comment]
@velkymx All other inspectors have the `name` field defined under the `Variable` accordion as `Key Name`:

<img width="148" alt="Screen Shot 2019-07-30 at 9 32 17 PM" src="https://user-images.githubusercontent.com/7561061/62177042-86451100-b311-11e9-946c-4d33d3949a77.png">

But `Image` is different:

<img width="189" alt="Screen Shot 2019-07-30 at 9 30 25 PM" src="https://user-images.githubusercontent.com/7561061/62177021-6ca3c980-b311-11e9-8a03-d0609ee9ae43.png">

Should `Name` be moved to `Key Name` under `Variable` to keep this consistent? It is modifying the same property, and would help eliminate some "special case" code just to handle `name` for `Image`.

**Comment by velkymx** [comment]
Lots on inconsistencies with the PR and the document.
