### ISSUE TITLE
Calc Props Modal

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#303]
if you are defining a new Computed/Calc Property using the modal popup window, you cannot click outside of the window or it will close abruptly and any unsaved progress will be lost. Since calc properties can rely on JS formulas, it is extremely inconvenient to lose work by a mis-click somewhere on the screen. The popup window should persist until the user actively presses one of its buttons (cancel, save property).

This would eventually be better served if not relying on a popup window at all, maybe through an inspector formula configuration at the right tab section, or whatever. But in the meantime, these calc properties popup windows must not be closed upon external clicks.

**Comment by chipit24** [comment]
@velkymx Just tested this and it appears to be fixed.
