### ISSUE TITLE
Unique Page Names

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#304]
Screen editor page names should be unique identifiers. Currently you can name the pages on one screen the same. There should be some validation for unique name on page tabs when one is created or existing one is edited.

**Comment by chipit24** [comment]
@nolanpro Do you have a PR for this?

**Comment by nolanpro** [comment]
@chipit24 I'm having an issue where i'm getting $deepModel not found in console when run in processmaker when I add a field to builder, could you take a look? Otherwise it works as expected. https://github.com/ProcessMaker/screen-builder/tree/feature/304
