### ISSUE TITLE
Controls / Footer Off Screen

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#306]
This is in Firefox and Edge

![image](https://user-images.githubusercontent.com/535300/61984640-23264800-afba-11e9-9927-be7e1472cb5d.png)

To Reproduce:

1. Create a new Screen
1. Try to add the File Download control to the page

Of note, once you start adding enough controls that the page can scroll vertically, the File Download Control appears.

This issue is also likely why the screen validation bar on the bottom of the page does not appear

**Comment by velkymx** [comment]
This is still persistent in Edge and Firefox.

![image](https://user-images.githubusercontent.com/535300/62964069-1de93b80-bdb7-11e9-9450-a6281916a1a8.png)

![image](https://user-images.githubusercontent.com/535300/62964081-2477b300-bdb7-11e9-975f-2b11e83880bf.png)

**Comment by chipit24** [comment]
@velkymx Can you provide more details please? I tested this again and it appears to still be fixed. I'm testing locally on the latest processmaker develop branch.

I tested this in Firefox 68 on macOS Mojave 10.14.5 and MS Edge 18 on Windows 10 (in BrowserStack).

It appears the scrolling issue in Edge is the same as the one reported in Safari, so I updated that ticket: https://github.com/ProcessMaker/screen-builder/issues/337. Note that that scrolling issue is one in which one scrollbar appears, but all the content is still accessible.

**Comment by velkymx** [comment]
Taylor says use flexbox correctly

**Comment by lisa-fehr** [comment]
Can't see it in stand-alone for MS Edge 18 / 17 on Win 10, but I can see it in processmaker. 

Didn't see an issue on Firefox or Safari on Mac.

**Comment by velkymx** [comment]
Closing. Will reopen if the issue resurfaces.
