### ISSUE TITLE
Date / Time Picker Broken

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#310]
I can only select the date, not the time. I'd also like to be able to type in a date.

**Comment by chipit24** [comment]
@velkymx what is the desired behaviour for the date / time picker?

Should two separate controls be used (a date picker and a datetime picker) or should the type of control change based on the chosen data type?

> I'd also like to be able to type in a date.

This part of the issue can be broken out, as it adds new functionality to the date control and will require additional work on top of fixing the current behaviour.

**Comment by chipit24** [comment]
I created a separate issue for the typing functionality: https://github.com/ProcessMaker/screen-builder/issues/313.
