### ISSUE TITLE
Decimal Type Validation

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#318]
Create a Screen
Add a Line Input with the Data Type set to "decimal"
Try to type:
100.0
0.100
.001
100.100

Result:
Depending on how you are using a decimal in your number, when trying to type decimals into a decimal data type line input, it says input is invalid, or it will remove the decimal entirely.

**Comment by sanjacornelius** [comment]
There is a [PR](https://github.com/ProcessMaker/vue-form-elements/pull/61) in `vue-form-elements` to close this ticket.
