### ISSUE TITLE
Invalid Screens Can Save

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#319]
Steps to Reproduce:

1. Go to a screen builder
1. Add a record list within a table and without a name
1. Save the screen

Current Behavior:

The screen saves...

![image](https://user-images.githubusercontent.com/535300/62478214-65404e00-b75f-11e9-8cc0-3a892c921524.png)

Expected Behavior:
The screen should not save with a missing name

**Comment by velkymx** [comment]
Duplicate

**Comment by ZLTM** [comment]
Still happening in feature/2264 

![RecordUnnamedSave](https://user-images.githubusercontent.com/7957742/63023290-cd371880-be72-11e9-9b53-0434dc6102ea.png)
