### ISSUE TITLE
Empty Dropdowns

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#326]
This latest version introduced a change to selects (dropdowns), something about Data Sources, that made all existing dropdowns blank

**Comment by chipit24** [comment]
@velkymx I can't reproduce this issue. I'm not having any noticeable problems with selects. Here is a video of it working: https://www.dropbox.com/s/owvh9pwcn7pvu2w/selects_working.mov?dl=0.

It was discussed that switching selects over to use Data Sources would cause problems with selects that were defined using the previous options config. If there are problems with selects, they should be updated using the new Data Source config and they should continue to work after.
