### ISSUE TITLE
Record List 

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#328]
Steps to Reproduce:

Create a screen with a record list

Configure it as specified in the documentation

Current Behavior:

The Record list won't work

2 warnings appear on the console

![image](https://user-images.githubusercontent.com/535300/62720083-21974f80-b9be-11e9-8dae-bd4adabd1cd6.png)

Expected Behavior:

The record list should be working as specified

https://www.dropbox.com/s/2ajqpns0satjpyl/RecordController.mp4?dl=0

**Comment by chipit24** [comment]
> Configure it as specified in the documentation

@velkymx can you post a link to the documentation? I'm not having any clear issues with the record list. Here is a video of it working for me: https://www.dropbox.com/s/7z3vr0jtu5e9ux8/record_list_working_03.mov?dl=0.

**Note:** The record list was missing a couple inspector fields, so I had to test with the latest changes from https://github.com/ProcessMaker/screen-builder/pull/329.

The deprecation warning is just a warning for when/if we upgrade the component, it's not currently the cause any errors.

**Comment by velkymx** [comment]
@chipit24 the record list should not contain the data source options. It should not have been changed and needs to be reverted.
