### ISSUE TITLE
Rich text editor not loading in processmaker

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/screen-builder#333]
The rich text editor fails to load in ProcessMaker with the following error:

```
[Vue warn]: Failed to resolve async component: function Editor() {
      if (typeof window !== 'undefined') {
        return Promise.all(/* import() | tinymce */[__webpack_require__.e(1), __webpack_require__.e(0)]).then(__webpack_require__.bind(null, "f61d"));
      }
    }
Reason: Error: Loading chunk 0 failed.
```

<img width="1059" alt="Screen Shot 2019-08-09 at 1 43 31 PM" src="https://user-images.githubusercontent.com/7561061/62798193-b330bb00-baab-11e9-853b-1e5c570512b0.png">

It appears the file that has been split out for the rich text component isn't available and results in a 404. The webpack config may need to be updated.

**Comment by nolanpro** [comment]
@chipit24 Added this here and it fixes it but not sure if this is the best way: https://github.com/ProcessMaker/processmaker/pull/2248

**Comment by chipit24** [comment]
@nolanpro I don't see a better way to do it. I actually just did the same fix (I copied over only the specific folders that were required instead of the entire directory though)!

**Comment by chipit24** [comment]
Closing this issue, was already open at https://github.com/ProcessMaker/processmaker/issues/2247.
