### ISSUE TITLE
Scroll bars not working correctly in Safari and Edge

### ISSUE THREAD

**Issue by chipit24** [ProcessMaker/screen-builder#337]
Testing on Safari 12.1.1 on macOS Mojave, it appears that only a single vertical scrollbar appears instead of multiple scrollbars.

Screenshot of bug:
<img width="1454" alt="Screen Shot 2019-08-12 at 10 58 35 AM" src="https://user-images.githubusercontent.com/7561061/62874980-275ba080-bcf0-11e9-84a7-cbac3559053a.png">

How the scrollbars should look:
<img width="1440" alt="Screen Shot 2019-08-12 at 10 59 53 AM" src="https://user-images.githubusercontent.com/7561061/62875065-55d97b80-bcf0-11e9-9a93-7e4f0ba0f2e8.png">

The validation footer should always be visible, and there should be separate scrollbars for the inspector controls list (left), the form builder (centre), and the inspector panel (right).

PR for fix is in the ProcessMaker Repo: https://github.com/ProcessMaker/processmaker/pull/2286

**Comment by tuantruong625** [comment]
Fix in ProcessMaker
https://github.com/ProcessMaker/processmaker/pull/2286
