### ISSUE TITLE
Looping Container Control

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#354]
PRD: [PM4-669679617-230120-1634.pdf](https://github.com/ProcessMaker/screen-builder/files/4104246/PM4-669679617-230120-1634.pdf)

Updated: https://processmaker.atlassian.net/wiki/spaces/PM4/pages/669679617/Screen+Builder+Looping+Containers#Updated-Design-Elements

I think what we are looking here is for a container of controls. If a patient has a list of prescriptions I may want to show a loop of rich text controls and file downloads for each of the prescriptions. Think of it as a container I can drag any of the controls into. The configuration of the control would be what variable contains the array to loop over and what would the local variable before the current indexed item.

**Comment by tdondich** [comment]
I think what we are looking here is for a container of controls.  If a patient has a list of prescriptions I may want to show a loop of rich text controls and file downloads for each of the prescriptions.  Think of it as a container I can drag any of the controls into.  The configuration of the control would be what variable contains the array to loop over and what would the local variable be fore the current indexed item.

**Comment by velkymx** [comment]
I'm wondering if we don't just add looping support to the rich text, checkbox or input controls...

**Comment by velkymx** [comment]
Icon for control: <i class="fas fa-redo"></i>
Label: Loop

**Comment by velkymx** [comment]
The loops should have the option to scope to a variable.

**Comment by velkymx** [comment]
@ryancooley we need a mock up

**Comment by velkymx** [comment]
Unfocused elements view.

![image](https://user-images.githubusercontent.com/535300/72923766-8e03d200-3d04-11ea-91db-e9425d9855a9.png)

**Comment by velkymx** [comment]
Focused loop container:

![image](https://user-images.githubusercontent.com/535300/72924032-04a0cf80-3d05-11ea-9afb-381b0f0af618.png)

**Comment by velkymx** [comment]
Inspector:

![image](https://user-images.githubusercontent.com/535300/72924346-9dcfe600-3d05-11ea-897a-af93157869a5.png)

**Comment by velkymx** [comment]
This feature does not satisfy the PRD requirements

**Comment by velkymx** [comment]
**Updated Design Elements**

Inspector: If the Data Source is New Array

![image](https://user-images.githubusercontent.com/535300/75994491-ea374580-5eaf-11ea-9fe1-c2cb1ef002ed.png)


Inspector: If the Data Source is Existing

![image](https://user-images.githubusercontent.com/535300/75994537-f91df800-5eaf-11ea-88de-77cae1bda2bc.png)


If the Additional Loops check box is selected, then, at run time, show a button that will allow additional loops to be added.

![image](https://user-images.githubusercontent.com/535300/75994565-04712380-5eb0-11ea-91ae-c2df455de5b5.png)

**Comment by nolanpro** [comment]
Fixed in https://github.com/ProcessMaker/screen-builder/issues/614
