### ISSUE TITLE
Select List Issues

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#359]
**First and foremost this needs to be a NEW CONTROL**

There are a few issues with the new select list.

1. The dropdown isn't rendering existing data

In the editor

![image](https://user-images.githubusercontent.com/535300/63733554-aa6f1180-c82d-11e9-9965-c5ceb65a3ca3.png)

In the task

![image](https://user-images.githubusercontent.com/535300/63733572-b6f36a00-c82d-11e9-8fc3-9e2b6b7550d4.png)

2. The layout doesn't match the PRD - I've attached the HTML, it's styled and ready to drop in.

Download here: [select-list-html.txt](https://github.com/ProcessMaker/screen-builder/files/3543796/select-list-html.txt)

Current implementation on the left, PRD on the right. Make sure all of the text matches (and translates).

![image](https://user-images.githubusercontent.com/535300/63733687-35e8a280-c82e-11e9-9c27-64a434defa0c.png)

3. Multi-Select Options

The dropdown for rendering should show the following options: 

Dropdown / Multiselect
Radio / Checkbox Group

In the event that "Allow Multiple Select" is checked, the rendering for the elements changes

Dropdown -> Multiselect
Checkbox Group -> Radio Button Group

4. Sidebar

Remove Radio Group (as it's a duplicate of above) and it should like like this:

![image](https://user-images.githubusercontent.com/535300/63733439-3e8ca900-c82d-11e9-95b7-3e17075f2258.png)

**Comment by danloa** [comment]
@velkymx what name will have the new Select List? Temporary we named it "PolySelect", for its Polymorphic nature. Other suggestions are "MultiCombo", "MultiList".
