### ISSUE TITLE
Variable accordion menu missing from Submit Button

### ISSUE THREAD

**Issue by ryancooley** [ProcessMaker/screen-builder#373]
![Screen Shot 2019-08-28 at 6 14 20 PM](https://user-images.githubusercontent.com/867714/63902741-b094f780-c9bf-11e9-94d8-2b14ecf787ea.png)

**Comment by chipit24** [comment]
Some more context:

The screen builder controls should contain the list of controls defined in https://docs.google.com/document/d/1xLekCTfdXJ8H_qlGs1mmEVO2UjRXIY-x73csCytDzsA/edit. For the submit button, this is:

<img width="225" alt="Screen Shot 2019-08-29 at 9 45 51 AM" src="https://user-images.githubusercontent.com/7561061/63945710-cc40e200-ca41-11e9-9a5f-bd5b0241fa62.png">

Looking at the screenshot posted above, it appears there is a _Configuration_ accordion which should be removed, and the _Variable_ accordion with _Key Name_ and _Value_ should be added.

**Comment by ryancooley** [comment]
Closed by #376.
