### ISSUE TITLE
Multi-Column Read Only Controls

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#384]
Story: Sometime I want to be able to display the form elements without allowing the user to make changes to them.

This functionality is already available in the input and textarea controls, but needs to be added to:

- [x] Selects
- [x] Radio Groups (so you can't change the selected radio
- [x] Date Picker
- [x] Checkbox

Add a checkbox to make a form element read only (see UI #249)

https://getbootstrap.com/docs/4.1/components/forms/#readonly

**Comment by velkymx** [comment]
@marcoAntonioNina when you are in a screen and the controls are read only inside of the multi-column, the don't work. 

**Design Time**

![image](https://user-images.githubusercontent.com/535300/66235779-b6a88300-e6a5-11e9-97b9-81ec73760db8.png)

**Preview**

![image](https://user-images.githubusercontent.com/535300/66235791-c2944500-e6a5-11e9-9a0e-65e704b2db09.png)

**Comment by marcoAntonioNina** [comment]
does not reproduce in the master branch

Design
![image](https://user-images.githubusercontent.com/1747025/69747174-3b4ed500-111c-11ea-84c7-d93e94143277.png)

Preview
![image](https://user-images.githubusercontent.com/1747025/69747202-4a358780-111c-11ea-9a84-69f8171e0732.png)
