### ISSUE TITLE
Currency Data Type

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#389]
As an end user I want to be able to specify a variable type (which we do) and have it change the way the data is displayed on both the forms and display screens.

- [x] Add Vue-The-Mask https://vuejs-tips.github.io/vue-the-mask/ - Nolan
- [x] Add Vue-Money https://vuejs-tips.github.io/v-money/ - Nolan
- [x] Add JSON file of all currency types - Sanja
- [x] Add Data Type "Currency" - to be saved as a FLOAT

![image](https://user-images.githubusercontent.com/535300/64439608-32031e80-d07f-11e9-8695-6bfc35ba8316.png)

- [x] Once Currency is selected, add new drop down for Currency Select with a list of world currencies (see PRD for list)

![image](https://user-images.githubusercontent.com/535300/64439810-ad64d000-d07f-11e9-9273-fe702764f871.png)

- [x] Store Currency format as metadata for the variable
- [x] Display FORM INPUT with mask using currency format

![image](https://user-images.githubusercontent.com/535300/64439931-de450500-d07f-11e9-8aee-92ea9c8792a6.png)

- [x] Display variable in DISPLAY screen formatted using mask
- [ ] Display variable in EMAIL screen formatted using mask
- [ ] Saved Search columns show format

![image](https://user-images.githubusercontent.com/535300/64439968-ed2bb780-d07f-11e9-9d7c-4e2dbf157f1f.png)

- [ ] DUSK Tests to confirm all use cases work

PRD: https://processmaker.atlassian.net/wiki/spaces/PM4/pages/569933863/Expanded+Display+Formatting

**Comment by velkymx** [comment]
For use in display something like {amount | currency('USD')}

**Comment by velkymx** [comment]
This is completely missing in Beta 10

**Comment by caleeli** [comment]
Requires change in vue-form-elements: https://github.com/ProcessMaker/vue-form-elements/pull/132

**Comment by caleeli** [comment]
This Ticket will require: https://github.com/ProcessMaker/vue-form-elements/pull/135
