### ISSUE TITLE
Multiple File Uploads override each other

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/screen-builder#401]
Needs https://github.com/ProcessMaker/processmaker/pull/2420

To reproduce
- create a screen with an editable record list
- create a new page in the screen to be used as the record list add/edit
- on that add/edit page, add a file upload

Result: the data object has the correct file names but only one file gets saved to the request

Test:
- Regular upload (not in record list) still works
- uploads work in collections (record list, known issue)

webenty - known issue

**Comment by PMQABen** [comment]
So far, unable to reproduce this in Chrome, Safari, Firefox, and MSE. With correct variable name usage on the file upload control, this is not occurring. Trying to get more information.

**Comment by tdondich** [comment]
Do it inside a record list

**Comment by PMQABen** [comment]
As long as you provide the proper upload variable names in a record list, the filenames display correctly.
