### ISSUE TITLE
Unresponsive Screens

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#403]
If a record list and multiple inputs (text, select, etc) are present, then the screen builder stops responding and the browser crashes.

**Comment by PMQABen** [comment]
https://staging-pm4.processmaker.net/designer/screen-builder/67/edit
Screen: [application_lookup.json.txt](https://github.com/ProcessMaker/screen-builder/files/3658988/application_lookup.json.txt) (remove .txt)
Potential repro steps:
```
1. opened screen designer
2. added record list to top of screen below top nav buttons
3. named record list "test"
4. tied to "loan information" tabe
5. added var in value as loanAmount
6. added label in content as Amount
7. went to preview mode
8. added one record
9. only entered info in loan amount field
10. clicked ok
11. clicked edit
12. clicked ok
13. tried to click "add record"
14. at that point resources locked up
```
