### ISSUE TITLE
Read-Only Toggle Broken

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#415]
If a form has a toggle/checkbox, this is not read-only when the submitted form is reviewed in the Forms tab. When you preview the submitted you can actually modify the toggle value. Which, if you have visibility rules added to the toggle value, will also trigger in the Form preview.

**Comment by danloa** [comment]
@velkymx  I can't reproduce the problem. All checkboxes of a screen  when previewed in the "Forms" tab are readonly (greyed out) and no events are triggered when clicking on them.
**Screen in Design Time:**

![image](https://user-images.githubusercontent.com/14875032/66863165-6dd3b280-ef60-11e9-9aa9-f95be8827c28.png)

**Screen in Forms tab:**
![image](https://user-images.githubusercontent.com/14875032/66863160-6c09ef00-ef60-11e9-94b1-b77db9ccbf7e.png)
