### ISSUE TITLE
Visibility Rules Not Respected

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#419]
In display and email screen type you should be able to hide and show content based on visibility rules. The content, upon rendering, is not respecting the display rules. Email screens should remove the hidden content and the forms should hide it.

**Comment by marcoAntonioNina** [comment]
i can't reproduce the problem

![visibleRules](https://user-images.githubusercontent.com/1747025/67098270-e1a4d380-f189-11e9-9bfc-54d39e8d0db5.gif)

**Comment by velkymx** [comment]
This is about the rules not being applied to the rendering when the form is generated.

**Comment by marcoAntonioNina** [comment]
working in screen types: Display, Form, Email
