### ISSUE TITLE
Number converting to exponential notation

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#437]
Steps to Reproduce:

Go to a screen with a decimal type line input
Insert a number with 6 repeating 0s followed by a number like 0.0000001
Click outside the controller
Current Behavior:
The number changes to scientifical notation, that's not accepted by the controller

Expected Behavior:
The number should not change automatically to an unaccepted notation

Could be an issue with mathjs. Needs investigation.

**Comment by tuantruong625** [comment]
In vue-form-elements repo the FormInput component parses the value on blur though the `formatFloatValue()`
```
formatFloatValue() {
      if ( this.dataFormat == 'float' && this.dataTypeValidator.passes() ) {
        this.value = Number(this.value);
        return this.$emit('input', this.value);
      }
    },
```
Passing `this.value` through the Number function will parse the decmial value to exponential notation.

A simple solution could be using parseInt() instead.

@velkymx

**Comment by JCook21** [comment]
@tuantruong625 `parseFloat()` isn't an option here: it also returns the number in exponential notation. I've been looking into this a bit and it isn't straightforward at all. We're going to postpone this for now but there are a couple of possible approaches:

- Don't cast the number to a floating point value. We could still ensure that it is valid using the regex though.
- Have the server accept exponential numbers. We would still need to format the number for display though, and `Number.toPrecision()` may provide the answer to that even though it returns the number formatted as a string.

**Comment by caleeli** [comment]
This is a Javascript Limitation. Javascript implements 64-bit Floating Point numbers following the international IEEE 754 standard (value: 52 bits, exponent: 11 bits and sign: 1 bit) That means the maximum number of digits (in decimal system) is **17**, from there the digits will be rounded and use the exponent notation. This will also happens when converting the objects to JSON notation.

Probably the best option to store this big numbers are Strings.

**Comment by JCook21** [comment]
@caleeli I'm not sure that storing numbers as strings is a great idea. I would see them stored as floating point numbers, with them being cast to strings for display purposes. Keeping the values as floating point numbers would help to avoid issues from casting and would help to ensure that the bad values are not stored in the DB (as long as they're stored as a float there).
