### ISSUE TITLE
Screen Builder freezes when adding a DatePicker inside a MultiColumn

### ISSUE THREAD

**Issue by danloa** [ProcessMaker/screen-builder#452]
To reproduce the problem:

- Create a new screen
- Add a Multicolumn
- Add inside the Multicolumn a DatePicker
- Using the inspector, configure the variable name of the DatePicker 
- Finally, configure the Data Type of the DatePicker. 

The screen will freeze as is shown in the next screenshot

![image](https://user-images.githubusercontent.com/14875032/69748900-ae0d7f80-111f-11ea-88fe-216b462e42d2.png)

**Comment by JCook21** [comment]
I can't reproduce this. I've tested this in Safari, Chrome and Firefox on MacOS with no issues running the latest screen-builder code from develop in standalone mode. If you're still seeing this issue please reopen and provide more reproduction steps.
