### ISSUE TITLE
Date Picker Locks Up Screen

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#458]
There is a problem where if you add a date picker to a screen and then give a key name to a variable, and then choose the variable type the entire browser freezes.

https://www.dropbox.com/s/fwdt60kl8nje3v8/datepicker-locks-ui.mp4?dl=0

**Comment by danloa** [comment]
This issue is resolved in vue-form-elements, the corresponding PR is:

https://github.com/ProcessMaker/vue-form-elements/pull/139
