### ISSUE TITLE
Select List: Select One String

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#495]
When you setup a variable to not be a multi-select the value should be passed as as string. Right now it is passing as an array.

https://www.dropbox.com/s/opj5yz4gy0av5gs/SelectListSingleArray.mov?dl=0

**Comment by danloa** [comment]
Resolved in vue-form-elements project. The PR is:

https://github.com/ProcessMaker/screen-builder/issues/495
