### ISSUE TITLE
Date Formatting Wrong

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#499]
![image](https://user-images.githubusercontent.com/535300/72361726-d4bf4f80-36a6-11ea-94d9-dacd5d53b725.png)

I tried using the YYYY-MM-DD , MM/DD/YYYY AND DD/MM/YYYY and they all format wrong.

**Comment by velkymx** [comment]
![image](https://user-images.githubusercontent.com/535300/72361879-06381b00-36a7-11ea-8b8d-e3c96efe9e71.png)

**Comment by velkymx** [comment]
![image](https://user-images.githubusercontent.com/535300/72362583-43e97380-36a8-11ea-9a04-c3f0ce4e3a1a.png)

**Comment by velkymx** [comment]
[Leave of Absence Request Form 4.json.txt](https://github.com/ProcessMaker/screen-builder/files/4060250/Leave.of.Absence.Request.Form.4.json.txt)

**Comment by lisa-fehr** [comment]
This seems to have something to do with the form-masked-input component
```javascript
getDateFormat() {
      return {
        type: 'date',
        masked: true,
        mask: this.getUserConfig().date_mask || '##-##-####',
      };
    },
    getDatetimeFormat() {
      return {
        type: 'datetime',
        masked: true,
        mask: this.getUserConfig().datetime_mask || '##-##-#### ##:##',
      };
    },
```

`new Date().toLocaleDateString()` is returning a date/time that does not contain leading zeros.
1/15/2020 -> 11-52-020 (##-##-####)

Not sure where to set `datetime_mask` and `date_mask` on the user - as it is going to the default mask. User input could affect the changes we make.

**Comment by lisa-fehr** [comment]
**Expected Outcome:**

It should take the data and use the user's date format setting.

**Comment by lisa-fehr** [comment]
Historical tickets for the datetime formatter:
https://github.com/ProcessMaker/vue-form-elements/issues/84
https://github.com/ProcessMaker/screen-builder/issues/390
