### ISSUE TITLE
Nested Screens

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#508]
Ability to render/nest a screen (display can only nest other display forms, a input screen can nest a display/input screen)

Configuration should include the screen and an OPTIONAL data variable to “scope” the sub-screen.  For example, I could put “customer” and it would map to the customer property.  If blank, it will reference the top-level of the data object.

**Comment by caleeli** [comment]
Implemented by: https://github.com/ProcessMaker/screen-builder/pull/518
