### ISSUE TITLE
Buggy Validation

### ISSUE THREAD

**Issue by sanjacornelius** [ProcessMaker/screen-builder#539]
**Issues:**

1. Ensure correct labels, descriptions & helper text display for rules. 
2. The rules config Input values are being inherited from elements.
3. Ensure the form does not submit when there are validation errors.
4. Ensure fields do not inherit other fields validation rules in preview mode & while running a process.

https://www.dropbox.com/s/eshu2p3tzsn4xgi/validation-buggy.mov?dl=0

**Comment by ZLTM** [comment]
Min and Max length no longer share values, the validation still changes as the user inputs values
this should be divided into two different tickets, one for the shared values, and one for the validation warnings

**Comment by ZLTM** [comment]
Working correctly on screen-builder
