### ISSUE TITLE
Record lists duplicating data & showing wrong headers

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#549]
When multiple record lists are on the same form, the columns on the first record list are showing on subsequent record lists on the display portion if the record lists are on a second page. Also, the record lists duplicate the data when on the same page in a form. 

![image](https://user-images.githubusercontent.com/535300/75128957-a0fb2080-567b-11ea-9c57-e7c91676ba3b.png)

In this thumbnail you can see businessName showing up in the background of the form. It was a field from the record list on the profile tab.

**Comment by ZLTM** [comment]
Fixed on develop

**Comment by velkymx** [comment]
https://www.dropbox.com/s/n5ksveduke3dz5t/recordlistsIssue549.mov?dl=0

**Comment by sanjacornelius** [comment]
@velkymx  Retested this ticket and I can confirm that this issue is not present on the lastest screen-builder 

https://www.loom.com/share/20a5f03a427d43fba3819680d72dc74a

**Comment by velkymx** [comment]
Great. Thank you

**Comment by bmackley** [comment]
✅Confirmed that this issue is working in the latest build.
