### ISSUE TITLE
Edit Record Empty

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#551]
**Steps to Reproduce:**
Create a Screen

Add a "Record list" with columns

Create a "Record form" page for column filling in the "Record list"

In a process add the Screen created

Start the case

Add a record to the "Record list"

Try to edit the record added

**Current Behavior:**

The fields in the "Edit Record" popup are empty 

**Expected Behavior:**

The data in the selected row for edition has to fill in the "Edit Record" popup

https://www.dropbox.com/s/ynodwd8hba603ze/Record.webm?dl=0

**Comment by sanjacornelius** [comment]
@velkymx  I cannot reproduce this issue.

<a href="https://www.loom.com/share/062ae4aad8bf48e9914278a80429be36"> <p>26 February, 2020 - Loom Recording - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/062ae4aad8bf48e9914278a80429be36-with-play.gif"> </a>

**Comment by PMQABen** [comment]
Can't reproduce this on 4.0.3dev.

**Comment by ZLTM** [comment]
Can't reproduce on 4.0.3, however, it did it reproduced on the preview of 4.0.2, not on the request, looks like it has been fixed

**Comment by velkymx** [comment]
Great. Closing
