### ISSUE TITLE
Watchers Broken on Multi-Screen Forms

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#553]
If I have a record list attached to the screen, the watcher is not executed and is producing the following error in Console:

```
app.js?id=db8ba300ba7e43539c64:204106 Uncaught TypeError: Cannot read property 'find' of undefined
    at VueComponent.loadWatcherResponse (app.js?id=db8ba300ba7e43539c64:204106)
    at app.js?id=db8ba300ba7e43539c64:204179
    at r.listener (app.js?id=db8ba300ba7e43539c64:292272)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
    at r.ondecoded (index.js:83)
    at a.<anonymous> (index.js:83)
```

Please find attached to this message the video with the details, additionally I imported the screen JSON File.

https://www.dropbox.com/s/weeeyzotefvydh0/ScreensandWatchers.mov?dl=0

[PO Request.json.txt](https://github.com/ProcessMaker/processmaker/files/4243109/PO.Request.json.txt)

**Comment by PMQABen** [comment]
Using the Process attached to the JIRA ticket for this (FOUR-1145): [Error-Purchase Order Form Process.json.txt](https://github.com/ProcessMaker/screen-builder/files/4300977/Error-Purchase.Order.Form.Process.json.txt)
I get the following error when the Watcher tries to run:
```
Uncaught (in promise) TypeError: Cannot read property 'synchronous' of undefined
    at VM2055 app.js:206299
```

**Comment by marcoAntonioNina** [comment]
@PMQABen I can't reproduce the issue in the branch develop.

**Comment by PMQABen** [comment]
Looks like it has been fixed at some point over the last 4 days. Watcher works as expected now.
