### ISSUE TITLE
Watchers Hang

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#554]
The watcher lookup for a simple screen takes too long to complete (over 4~5 minutes)

![image](https://user-images.githubusercontent.com/535300/75129541-4616f880-567e-11ea-9cf5-1249463b5d5d.png)

[Invoice Submission.json.txt](https://github.com/ProcessMaker/screen-builder/files/4243120/Invoice.Submission.json.txt)

**Comment by chipit24** [comment]
When I try to import the JSON file you provided, I get the following error:

<img width="1149" alt="Screen Shot 2020-02-27 at 10 44 36 AM" src="https://user-images.githubusercontent.com/7561061/75460534-94aee600-594f-11ea-8693-9cfe08d2cb8a.png">
 
The warning at the top says the screen was imported but nothing was actually imported.

**Comment by PMQABen** [comment]
Rebuilt the screen for 4.0.3: [Watcher Lockup Test.json.txt](https://github.com/ProcessMaker/screen-builder/files/4263513/Watcher.Lockup.Test.json.txt)
I can't get the watcher issue to reproduce locally, but on the develop.spark.qa.processmaker.net server, it occurs each time. Not sure what's up.

**Comment by ZLTM** [comment]
Can't reproduce on 4.0.3, tested with 'Watcher Lockup' since 'Invoice submission' is not importing

**Comment by velkymx** [comment]
OK will close. If reported again we'll reopen
