### ISSUE TITLE
Watchers not respecting Variable Names

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#556]
I've been trying to use a single simple LUA script for multiple Watcher variables, and instead of returning a unique output variable for each Watcher, it overwrites the first variable. I'm not sure if this is a potential use case of Watchers or not, but it's something I came across while playing with this feature.

https://www.dropbox.com/s/6x861ckac6tk4je/watchers-multiple-vars.mp4?dl=0

**Comment by marcoAntonioNina** [comment]
Is already corrected in the current branch.

**Comment by PMQABen** [comment]
Confirmed, working correctly in 4.0.3dev.
