### ISSUE TITLE
Watchers can duplicate themselves

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#557]
This has been a hard one to get exact reproduction steps, I've seen it happen after any of the following:

1. Edit the name of the second watcher
2. Flip to the preview panel, run a watcher test, then go back to the watcher modal
4. Edit a watcher config

If I can find 100% steps I will update this ticket. For sure though, once the watchers have duplicated, if you save the Screen, the duplicate will be saved, and when you delete one, both will be removed.

**Comment by PMQABen** [comment]
I poked at this issue again in the latest code for 4.0.4 and I can't make it reproduce no matter how I try. I'm going to suggest we close this ticket, and if it comes up again we can reopen it.
