### ISSUE TITLE
Options props is deprecated

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#558]
Deprecation warning for add sortable. Create/Edit a form-type screen. Open dev tools, go to the console

Options props is deprecated, add sortable options directly as vue.draggable item, or use v-bind. 

See https://github.com/SortableJS/Vue.Draggable/blob/master/documentation/migrate.md#options-props

**Comment by ZLTM** [comment]
I'm still seeing this on dev

**Comment by ZLTM** [comment]
Fixed on last screen-builder's pull
