### ISSUE TITLE
Nested submit button does nothing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#559]
**Steps to Reproduce:**

Have a screen with another screen nested in

Have the nested screen use a submit button

Run the screens

Press on the nested submit button

**Current Behavior:**

The button does nothing

Expected Behavior:

Remove / Hide submit button in the nested screen

https://www.dropbox.com/s/opzt2x35p5s5l5d/nestedSubmit.mp4?dl=0

**Comment by ZLTM** [comment]
The submit buttons configured on a nested screen still show and are unusable

**Comment by ZLTM** [comment]
Waiting for merge on the processmaker project
