### ISSUE TITLE
Nested Screen Timeout

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#560]
Create or upload at least 11 or more screens

Create a form-type screen, add a nested screen control

Search for a nested screen by entering a long string of characters

Result:

Because the search is happening immediately after entering a character, instead of waiting for a pause in typing, there are instances where a search will hit the 5 second API timeout because it's trying to juggle a sudden spike in API requests for the same end point.

Expected:

Can we find a way to wait for a 0.5-1s pause in user entry on the search box before submitting to the API endpoint?

**Comment by chipit24** [comment]
[`Debounce`](https://lodash.com/docs/4.17.15#debounce) or [`throttle`](https://lodash.com/docs/4.17.15#throttle) would be perfect for this.

**Comment by ZLTM** [comment]
working on dev
