### ISSUE TITLE
Nested Screen and Magic Variables

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#563]
1. Create a form-type Screen using one or more magic variables: _user.id, _user.fullname, _request.status, etc.
2. Create a second form-type Screen, add a Nested Screen control and configure it to use the first Screen
3. Create a Process, add a Task to use the first Screen created
4. Add a second task to use the second Screen
5. Run the process

**Result:**
When inside a nested screen, the Magic Variables do not populate and display.

**Expected:**
When inside a nested screen, the Magic Variables display correctly.

**Comment by caleeli** [comment]
Could you share the screens and the process?
Does de first screen has a submit button?
Does the second screen has two submit buttons?

**Comment by ZLTM** [comment]
Working on dev, tested it using these screens:

[Company.txt](https://github.com/ProcessMaker/screen-builder/files/4281355/Company.txt)
[Company details.txt](https://github.com/ProcessMaker/screen-builder/files/4281356/Company.details.txt)

**Comment by PMQABen** [comment]
It is not working. We need to wait for the next version of Screen Builder (0.22) to get merged with PM4 so we can test this properly.
