### ISSUE TITLE
Nested Screens Custom CSS

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#565]
1. Have two screens with different custom CSS rules
2. Reference one page in the other using the nested controller
3. Go to preview

**Current Behavior:**
Only the last applied CSS remains

**Expected Behavior:**
Keep the respective CSS of each page so that no changes will happen when nesting screens

https://www.dropbox.com/s/1t0uup4f4o0fmra/CSSBlocksCSS.mp4?dl=0

**Comment by chipit24** [comment]
@velkymx I'm not seeing issues with custom CSS and nesting.

I have the following setup:
<img width="458" alt="Screen Shot 2020-02-26 at 4 44 12 PM" src="https://user-images.githubusercontent.com/7561061/75390964-3cc4a080-58b7-11ea-9b64-3d24f599933c.png">

The yellow ("Screen A") is the top level screen, and it's nesting the the blue screen, and the blue screen is nesting the orange screen. All backgrounds are applied using custom CSS and they appear to be rendering correctly.

This is the view from the 2nd (blue) screen:
<img width="452" alt="Screen Shot 2020-02-26 at 4 46 11 PM" src="https://user-images.githubusercontent.com/7561061/75391158-9200b200-58b7-11ea-90cd-36b3abd82595.png">

And this is the view from the final (orange) screen:
<img width="451" alt="Screen Shot 2020-02-26 at 4 46 14 PM" src="https://user-images.githubusercontent.com/7561061/75391179-95943900-58b7-11ea-9e1c-29d58b9b9002.png">

The pink background between the blue and the orange in the 1st screenshot is from the custom CSS applied to the nesting container in screen A, which also renders as expected.

**Comment by PMQABen** [comment]
Can't reproduce #565 so far, waiting for feed back from the original issue reporter.

**Comment by velkymx** [comment]
The nested screen CSS should be scoped already. The problem will be, that the nested screen, will inherit the css rules, but any explicit rules in the nested screen will be utilized.

That's to be expected.

**Comment by ZLTM** [comment]
Cant reproduce on 4.0.3
