### ISSUE TITLE
Nested Screen Infinite Loop

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#566]
Steps to Reproduce:

Have 2 screen calling each other with the nested controller 
(screen A calls B, Screen B call A)

Go to screen preview

Current Behavior:
The screens loop over each other indefinitely

https://www.dropbox.com/s/dqqmbylgpschjr8/loopingNested.mp4?dl=0

**Comment by velkymx** [comment]
I'm open to ideas on how to solve this issue.

**Comment by chipit24** [comment]
@velkymx We've thought of a possible solution to this called the "my child cannot be one of my ancestors". Each _Nested Screen_ component will climb up its parent tree and collect the name of all it's parent screens. If the screen it wants to render is contained in this list, it won't render, preventing a possible cycling / infinite loop.

This would render all the screens up but not including the screen that would cause an infinite loop.

Using your example, Screen A would call Screen B, but before the nested screen component renders its referenced screen, it will ask itself, "is my parent the same as my child?" And if so, it won't render its child.

**Comment by velkymx** [comment]
@chipit24 as long as we surface an error message that calls it out.

**Comment by chipit24** [comment]
The solution we ultimately ended up going with is passing down an array of rendered screens to each nested screen renderer and preventing re-rendering a screen which has already been rendered, thus preventing an infinite loop.
