### ISSUE TITLE
Validation Min/Max Text

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#568]
- Create a Form-type Screen
- Add any control that can use validation rules
- Select "Min Length" and save

**Result:**
Text shows "Max Input" ... "Validate that an attribute is at least a given size."

**Expected:**
Text shows "Min Input" ... "Validate that an attribute is at least a given size."

Optionally, we could change "a given size" to "a given length", since we're talking about the number of characters in a field.

**Comment by ZLTM** [comment]
Still happens on develop

**Comment by ZLTM** [comment]
Working on screen-builder
