### ISSUE TITLE
No Record List Form Warning

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#569]
Add the Record List control to the Screen. Do not configure the control beyond the required settings.

Click Preview.

Result:
The following error message displays:

![image](https://user-images.githubusercontent.com/535300/75130258-2c77b000-5682-11ea-881b-a35946198f1d.png)

Please remove the second period from the message. Also, change “Save” to “OK” since you’re not saving anything; instead, you’re acknowledging the message.

**Comment by ZLTM** [comment]
Replicates on development

**Comment by johnblackspear** [comment]
Hi there @ZLTM 

It seems to have the second period removed and the button text changed to "OK" on core @ latest develop. Would you mind checking if it's perhaps related to a linking issue to `screen-builder` please?

![image](https://user-images.githubusercontent.com/28595383/75788939-d7fac180-5d60-11ea-919c-4e4afe7c0c99.png)

**Comment by ZLTM** [comment]
Just checked on the screen-builder project. everything working correclty
