### ISSUE TITLE
Multi-Column Validation Number of Columns

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#570]
When setting up a multi-column layout, make sure that they columns always add up to 12. If they don't then a warning should be show. In addition, negative column number should not be allowed.

**Steps to Reproduce:**

1. go to a screen with a multicolumn
2. Set it to use 12 columns
3. Create a new entry on the JSON with a negative number
4. Add a column with the same value but positive using the GUI

**Current Behavior:**
The negative value subtracts from the total (6+6= 12, 12-6=6) allowing the user to input more columns

**Expected Behavior:**
User should not be able to use a negative row number on the JSON.

**Comment by ZLTM** [comment]
![image](https://user-images.githubusercontent.com/7957742/75774039-78cb8b80-5d25-11ea-88ca-d374c26ba707.png)
It's still possible to add more than 12 rows, and negative numbers, to the multicolumn controller

**Comment by ZLTM** [comment]
Working correctly on the screen builder project
