### ISSUE TITLE
Multi-Page Forms Not Scrolling to Top

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#571]
When filling out a multi-page form in a Task, if the user clicks the "Next" button to go to the next page of the multi-page form, the following page shows the bottom of the form--not the top. The user must scroll up the form to see the top. To provide better usability, it would be great if the top of the form displays when the Next/Back buttons are used.

**Comment by ZLTM** [comment]
Fixed on development

**Comment by velkymx** [comment]
@nolanpro this isn't working on the web entry forms.
