### ISSUE TITLE
Multi-Column CSS Not Working

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#572]
Steps to Reproduce:

Go to a screen with a table

Change the color of its contents using custom CSS

**Current Behavior:**
The custom CSS is not applied

https://www.dropbox.com/s/gy74168tv1lxv06/TableCustomCSS.mp4?dl=0

**Comment by ZLTM** [comment]
Still failing on dev

**Comment by ZLTM** [comment]
Working on screen-builder
