### ISSUE TITLE
Existing Data Missing In Record Lists

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#573]
**Current behavior:** 
Variables aren't pulled into a record list form.  

**Expected behavior:** 
Variables should be accessible in a record list. 

https://www.dropbox.com/s/8wzd771jfc4nipq/Variables%20in%20Record%20Lists.mov?dl=0

**Comment by ZLTM** [comment]
Cant see more than one column on preview ow development, works normally on request
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/7957742/75784881-43309d80-5d39-11ea-84bd-cb3aa421a664.gif)

**Comment by ZLTM** [comment]
Working on screen-builder's preview, waiting for merge with processmaker
