### ISSUE TITLE
Submit Fails with Validation On Record List Form

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#576]
The submit button doesn't work when an editable Record List contains a 'required' field. This issue could be due to the submit button validating the form fields within the 'Add Record Modal'.

https://www.dropbox.com/s/8cuj6xo869kjykv/24%20February%2C%202020%20-%20Loom%20Recording.mp4?dl=0

**Comment by ZLTM** [comment]
Replicates on development

**Comment by ZLTM** [comment]
Working on scree-builder
