### ISSUE TITLE
Multicolumn with Record Lists

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#582]
When adding a editable Record List to a Multi-column the 'Add Record' modal does not display the associated form/page.

![image](https://user-images.githubusercontent.com/535300/75300196-fa825d00-57eb-11ea-8f1e-c6ff615bf64e.png)

**Comment by ZLTM** [comment]
![image](https://user-images.githubusercontent.com/7957742/75774650-c7c5f080-5d26-11ea-8826-e2c9219821d1.png)
Still no display in today's pull from dev

**Comment by ZLTM** [comment]
![image](https://user-images.githubusercontent.com/7957742/75879276-7d5d7600-5df1-11ea-8d06-4f189e36a332.png)
I can still see the behavior on the screen-builder project

**Comment by bmackley** [comment]
✅Record lists now function as expected when nested in tables. 
![image](https://user-images.githubusercontent.com/6541727/76225379-cdbe4480-61f2-11ea-9b7a-1fa5e924f914.png)

**Comment by sanjacornelius** [comment]
Hey @bmackley the issue occurs when running a process with a Record List. There is a PR open now with a fix.
