### ISSUE TITLE
Watchers Data Connectors Not Returning All

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#591]
The watcher drop down is only returning 10 or so results. It should return ALL results for scripts and connectors

https://www.dropbox.com/s/i1uy19y8tj876yl/oBCFXrC7aF.mp4?dl=0

**Comment by tuantruong625** [comment]
The lastest develop branch does not have the `Data Connectors` link. 
Which branch/build has this screen?

<img width="1676" alt="Screen Shot 2020-02-27 at 10 32 55 AM" src="https://user-images.githubusercontent.com/26545455/75459074-d68a5d00-594c-11ea-9401-00ef4158f91b.png">

**Comment by velkymx** [comment]
Ah. Ok just confirm the Scripts are returning all. That will satisfy this ticket. I'll add a ticket to the Data Connectors to fix it there.
