### ISSUE TITLE
Watcher Trying to POST with a GET

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#593]
If a Data Connector is configured as part of a watcher, and if the Data Connector is a GET it tires to do a POST instead of a GET.

https://www.dropbox.com/s/ug25uoc92xw5r77/tSHr0KuwJo.mp4?dl=0

**Comment by PMQABen** [comment]
I'm still able to get the POST error on my local machine by following the steps in the video, but using a line input control and typing 6+ characters in quick sequence. When using a select list as in the video, I don't get any errors, but I don't get any success either.

I'm at a loss.

**Comment by PMQABen** [comment]
Nolan got a fix in for Data Sources, and when I applied that to my local VM install, things worked correctly.
