### ISSUE TITLE
Calculated Properties

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#594]
Make sure that the term Calculated Properties is used everywhere. Currently it's presented as Computed.

**Comment by johnblackspear** [comment]
Alan - just to clarify: this is just the copy (e.g. titles and so forth) that you want changed?

Do you want us to look for and change any references outside screen builder too? I know this is referenced in core's translations too

**Comment by ZLTM** [comment]
'Computed properties' still appears on:
 Screen edit > Calcs > Header

**Comment by johnblackspear** [comment]
Hi @ZLTM can you tell me more about your setup? Having trouble replicating what you are seeing.

This is core @ latest develop:

![Mar-03-2020 09-26-50](https://user-images.githubusercontent.com/28595383/75785103-1f7e4f00-5d5b-11ea-8663-31f4a1ed28c7.gif)

**Comment by johnblackspear** [comment]
@ZLTM apologies for my pretty rough brain-hiccup earlier this morning.

I had to rebuild and re-link `screen-builder` too for core to get it to display right. I've grepped through the repos and I cannot find references to the `Computed Properties` string so I think it should work.

Screenie:
![image](https://user-images.githubusercontent.com/28595383/75788494-36737000-5d60-11ea-9b3a-769cb4a0a471.png)


Please do shout if it still persists after re-linking latest `screen-builder`.

**Comment by ZLTM** [comment]
@johnblackspear My bad, I was working on the incorrect environment, it is working as expected
