### ISSUE TITLE
New Loop Iteration

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#598]
Use case: As a user I'd like to be able to add an additional loop when using a screen. 

In the configuration: Add a checkbox for "Allow additional loops"

In the rendered screen, add a button [+ row] under the last loop item. Click on the button will trigger a new, unfilled, loop.

**Comment by josemaldonad0** [comment]
we need to also keep in mind that screen designers will want to be able to leverage data from row _i_ in their calc props or watchers, even without knowing how many rows will be added in runtime. Or that math applied within a loop (subtotal calc prop of values of other fields within the loop row) will be automatically applied to each new iteration. Sounds reasonable but currently not straightforward with Record Lists. So we should aim to not paint ourselves into a corner as it seems we've done with those.
