### ISSUE TITLE
Embedded Screen Validation Not Working

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#605]
The new bug I found is that the parent screen Submit Button is not validating the Nested Screen inputs. If the embedded screen has validation rules they should be run just like the other screen controls.

**Comment by sanjacornelius** [comment]
@velkymx  Can't reproduce. This is with the latest on develop. 

<a href="https://www.loom.com/share/e75d052331e14d53a27125fc3a9cdad6"> <p>2 March, 2020 - Loom Recording - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/e75d052331e14d53a27125fc3a9cdad6-with-play.gif"> </a>
