### ISSUE TITLE
Duplicate Control

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#621]
As a screen designer I'd like to be able to duplicate a control with a single click.

- [x] Add a button to the control header `<i class="fas fa-copy"></i>`
- [x] Clicking button makes a copy of the complete config below the element

![image](https://user-images.githubusercontent.com/535300/76106578-027c9280-5f8c-11ea-9362-4825b93ec230.png)

**Comment by sanjacornelius** [comment]
Closing. Merged in 4.0.3

**Comment by PMQABen** [comment]
They duplicate, but they duplicate at the bottom of the page, not just below the element that has been duplicated. Is this expected behavior?
