### ISSUE TITLE
Advanced Default Value

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#622]
As a "power" user I want to be able to make the default value of my control more complex. 

![image](https://user-images.githubusercontent.com/535300/76108521-9d2aa080-5f8f-11ea-85d9-1231e4692962.png)

Calc Default Value - should be reactive until the user edits the value - then the formula is not used

![image](https://user-images.githubusercontent.com/535300/76108556-a9166280-5f8f-11ea-94b3-105e18af47f4.png)

**Comment by PMQABen** [comment]
Advanced default values are currently not working.

**Comment by nolanpro** [comment]
@PMQABen please try again since fixing in #662

**Comment by PMQABen** [comment]
Good to go.
