### ISSUE TITLE
Loops inside Multi-Columns

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#638]
Loops inside MCs don't render properly -content disappears.
Reproduce:
1. Add multicolumn to form screen
2. Add Loop below multicolumn
3. Add a few elements to Loop (textbox, checkbox, etc)
4. Drag loop into mc above
5. Notice how loop content disappears and does not render correctly, either in designer or Preview.
...
6. Profit.

**Comment by PMQABen** [comment]
Going to re-open this, issue is occurring in 4.0.4. If the multicolumn control is added below the loop, then dragged into the loop, it works fine. If it is added above the loop, then dragged into the loop, it disappears.

**Comment by PMQABen** [comment]
Further testing shows this happens for **_all_** controls, as long as the control is above the loop before being dragged into the loop.

**Comment by nolanpro** [comment]
From the discussion this morning, added a separate issue here: https://github.com/ProcessMaker/screen-builder/issues/681

**Comment by velkymx** [comment]
This is a known issue.
