### ISSUE TITLE
Date Field Default Values

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#645]
When a default value is set for the date fields the input is blank.

**Comment by nolanpro** [comment]
Fixed as part of https://github.com/ProcessMaker/screen-builder/issues/622

**Comment by swim-mer** [comment]
Unable to make Default Values work via string or js.

**Comment by nolanpro** [comment]
@swim-mer please try again since i've done #662

**Comment by PMQABen** [comment]
Looks good.
