### ISSUE TITLE
Date Picker Limits

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#655]
As a user I want to be able to limit the dates in which can be selected. 

Ex: Not allow any dates before a certain date
Ex: Only allow dates between two dates

Need to expose these options in the UI

http://eonasdan.github.io/bootstrap-datetimepicker/Options/

**Comment by PMQABen** [comment]
[Vue warn]: Error in render: "Error: Validator `date_or_mustache` is not defined!"
found in
---> <App> at src/App.vue
       <Root>

**Comment by PMQABen** [comment]
When using "datetime" for the date picker, and the max date set to 2020-12-31, you cannot choose that date, can only choose 2020-12-30 or earlier. The same issue also occurs when using mustache syntax to set a max date.

----
Console error:
```
[Vue warn]: Error in callback for watcher "config": "TypeError: minDate() date parameter is after options.maxDate: 12/31/2015"
found in
---> <DatePicker> at component.vue
       <FormDatePicker>
         <VueFormRenderer>
           <ScreenBuilder> at resources/js/processes/screen-builder/screen.vue
             <Root>
```
Steps:
1. Add two date pickers
2. For the second date picker, set the minimum date to 2010-01-01, and the maximum date to be the mustache variable of the first date picker
_(this is a User Configuration error, but it still throws a console error)_

----
This may or may not be a related issue, but the arrow icons to change the hour:minute no longer work, they just return the user back to the calendar date list.

**Comment by ZLTM** [comment]
using minimum date causes errors to appear on the console, also preview won't open and clicking on it creates more errors 
![image](https://user-images.githubusercontent.com/7957742/78789487-311ace00-797b-11ea-9258-36faf5acd9d9.png)

**Comment by velkymx** [comment]
@ZLTM @PMQABen are you using the latest Screen builder? This is working fine on develop

**Comment by PMQABen** [comment]
2 days ago the issues I saw were on the develop branch, and the issues David saw were the same that I saw. On the latest develop branch on my VM for today, they are working.
