### ISSUE TITLE
Remove Loop

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#661]
If a user accidentally adds an additional loop, they'd like to be able to remove it. 

- [x] Show a confirmation modal, "Are you sure you want to delete this?"
- [x] Show a Minus button to the right of the plus. Make it outline / danger

![image](https://user-images.githubusercontent.com/535300/78808011-af767080-7979-11ea-9156-c00615566fae.png)

```
<a href="" class="btn btn-sm btn-outline-danger"><i class="fas fa-minus"></i></a>
```

**Comment by PMQABen** [comment]
If a user chooses the remove loop icon after all loops have been deleted, console errors are thrown:
```
[Vue warn]: Error in getter for watcher "times": "RangeError: Invalid array length"
found in
---> <FormLoop>
       <VueFormRenderer>
         <ScreenBuilder> at resources/js/processes/screen-builder/screen.vue
           <Root>

[Vue warn]: Error in callback for watcher "times": "RangeError: Invalid array length"
found in
---> <FormLoop>
       <VueFormRenderer>
         <ScreenBuilder> at resources/js/processes/screen-builder/screen.vue
           <Root>

[Vue warn]: Error in render: "RangeError: Invalid array length"
found in
---> <FormLoop>
       <VueFormRenderer>
         <ScreenBuilder> at resources/js/processes/screen-builder/screen.vue
           <Root>
```

**Comment by velkymx** [comment]
@nolanpro Make is so they can only remove loops if there more than 1. They cannot delete the initial loop.
