### ISSUE TITLE
Rich Text Editor Docked

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#665]
I'd like to doc the toolbar for the Rich Text in the text area to the top of the text box. No other changes to it but that. Also can we do something about the blue highlight around the editor box?

Layout like this:

![image](https://user-images.githubusercontent.com/535300/79392166-ca238900-7f27-11ea-85c7-6e83dbfdf29d.png)

Instead of this:

![image](https://user-images.githubusercontent.com/535300/79392253-f2ab8300-7f27-11ea-9bc5-25352966557c.png)

**Comment by nolanpro** [comment]
Fixed in https://github.com/ProcessMaker/vue-form-elements/issues/180
