### ISSUE TITLE
Empty Record List

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#684]
On this alert: 

![image](https://user-images.githubusercontent.com/535300/80983815-dfcaf680-8de1-11ea-9393-6928d3fb4e39.png)

Remove alert outline and just show the warning message in black text.

Furthermore the grammar of this message is awful. Change to:

`This record list is empty or contains no data.`

**Comment by PMQABen** [comment]
@ryancooley @velkymx Don't forget we need to update the en.json file for the changed string, and potentially need to get the es/fr/de strings updated.

**Comment by ryancooley** [comment]
> @ryancooley @velkymx Don't forget we need to update the en.json file for the changed string, and potentially need to get the es/fr/de strings updated.

Yup, already took care of that! Just waiting on Smartling now.
