### ISSUE TITLE
Validation Edit Missing Action Buttons

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#691]
While I know that changing the values will automatically update, it's confusing to users that there is no way to save and close the dialogue. 

![image](https://user-images.githubusercontent.com/535300/81100153-e41a1100-8ec0-11ea-96fd-a6fd982de8ff.png)

Add buttons to the bottom of the dialogue such as these:

![image](https://user-images.githubusercontent.com/535300/81100206-fdbb5880-8ec0-11ea-9121-f8123adeb93d.png)

Clicking update closes the forms and returns to the validation rules list:

![image](https://user-images.githubusercontent.com/535300/81100264-1c215400-8ec1-11ea-8bf4-94f9f361ba09.png)

**Comment by PMQABen** [comment]
Pressing the cancel button throws a console error:
```
vendor.js?id=ae3b4d4f2f0e720a855e:115688 [Vue warn]: Error in v-on handler: "SyntaxError: Unexpected token u in JSON at position 0"
found in
---> <ValidationSelect>
       <BCollapse>
         <VueFormBuilder>
           <ScreenBuilder> at resources/js/processes/screen-builder/screen.vue
             <Root>
```

**Comment by velkymx** [comment]
Console error when pressing Cancel button

**Comment by PaolaPellegrini** [comment]
Skip the following error when I perform the following steps:

I add a max lengh
I add a min lengh
I try to add another max or min lengh (it indicates that it already exists)
I add In

`vendor.js:115688 [Vue warn]: Error in callback for watcher "selectedOption": "TypeError: Cannot read property 'content' of null"

found in

---> <ValidationSelect>
       <BCollapse>
         <VueFormBuilder>
           <ScreenBuilder> at resources/js/processes/screen-builder/screen.vue
             <Root>
warn @ vendor.js:115688
logError @ vendor.js:116947
globalHandleError @ vendor.js:116942
handleError @ vendor.js:116902
run @ vendor.js:119623
flushSchedulerQueue @ vendor.js:119365
(anonymous) @ vendor.js:117043
flushCallbacks @ vendor.js:116969
Promise.then (async)
timerFunc @ vendor.js:116996
nextTick @ vendor.js:117053
queueWatcher @ vendor.js:119457
update @ vendor.js:119597
notify @ vendor.js:115799
reactiveSetter @ vendor.js:116124
proxySetter @ vendor.js:119684
callback @ app.js:176600
invokeWithErrorHandling @ vendor.js:116917
invoker @ vendor.js:117242
invokeWithErrorHandling @ vendor.js:116917
Vue.$emit @ vendor.js:118943
removeElement @ app.js:135387
select @ app.js:135387
click @ app.js:135387
invokeWithErrorHandling @ vendor.js:116917
invoker @ vendor.js:117242
original._wrapper @ vendor.js:122601
vendor.js:116951 TypeError: Cannot read property 'content' of null
    at app.js:176946
    at Array.find (<anonymous>)
    at VueComponent.handler (app.js:176945)
    at Watcher.run (vendor.js:119621)
    at flushSchedulerQueue (vendor.js:119365)
    at Array.<anonymous> (vendor.js:117043)
    at flushCallbacks (vendor.js:116969)`
Verificated in :  https://release-testing.processmaker.net/ 

The solutions  in not  approved

**Comment by PaolaPellegrini** [comment]
The verification of the solution has been carried out, and the following has been found:

Video --: https://drive.google.com/open?id=11EDSRxRmee2CgS2YJ-9VhR-WNGApNP7D

1. When we choose some elements and do not save them, the chosen element is not saved in the dropdown and when trying to save the error occurs. 
the elements are: After Date, Min, Before or Equal to Date, After or Equal to Date, Before Date, After Date.
Image error 1.  https://drive.google.com/open?id=1va_XzOvftjXN4YmxTqGas2iyQjd0ygEY

2. When the console is broken with error 1. When creating a new check box, another error jumps.
Image error 2.  https://drive.google.com/open?id=1PgKGF2kG9cXXseJpVNXxRstIhWDG949i

The solution is rejected

**Comment by PaolaPellegrini** [comment]
The problem continues to be replicated with the following steps:
- Select a control
- Add rules
- I add any rule, for example Email
- I choose the Email rule again
- Save

Console error becomes visible

See  the video  https://drive.google.com/open?id=1pjjnWmgzWCEBggIYDJJWaLWhejMYtGVF

The ticket  is  Rejected

**Comment by PaolaPellegrini** [comment]
DONE!
