### ISSUE TITLE
Console error when navigating between pages with richtext-enabled textarea controls

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#712]
Create a two page form screen:

Page one should have:

Multi-column table, with a richtext-enabled textarea control inside

Page navigation control set to page two

Page two should have:

Multi-column table, with a richtext-enabled textarea control, set to read-only

Page navigation control set to page one

Go to preview, open the browser error console, click the page navigation to move to page two

Click the page navigation to move back to page one

**Result:**
```
[Vue warn]: Error in callback for watcher "rows": "TypeError: Cannot read property 'style' of null"
found in
---> <FormTextArea>
       <FormMultiColumn>
         <VueFormRenderer>
           <ScreenBuilder> at resources/js/processes/screen-builder/screen.vue
             <Root>
```

**Comment by PMQABen** [comment]
Fixed.
