### ISSUE TITLE
Checkbox Checked By Default

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#723]
If a checkbox is checked by default, then the value should already be set on page load.

Current behavior

![image](https://user-images.githubusercontent.com/535300/82058227-4de0aa80-9679-11ea-98e7-ed3ea3d499a1.png)

Correct behavior

![image](https://user-images.githubusercontent.com/535300/82058264-5f29b700-9679-11ea-87a2-0df473859080.png)

**Comment by danloa** [comment]
This issue is resolved with this PR  from vue-form-elements:

https://github.com/ProcessMaker/vue-form-elements/pull/191

**Comment by ZLTM** [comment]
Working on 4.0.5

**Comment by velkymx** [comment]
@danloa if the checkbox is unchecked by default the variable should be set on page load as the value FALSE

**Comment by PMQABen** [comment]
Checkboxes now correctly show true or false in the initial data preview.

However,  checkboxes are now showing up defaulting to "read only", and also look checked when the "checked by default" option is not chosen. Even if the user toggles the "checked by default" option on and off, the appearance in the builder does not change.

**Comment by velkymx** [comment]
@PMQABen we are also seeing this. 

When you first go to configure an element it checks the checkbox on focus. Seeing similar behavior in Modeler when you add a Form Task - it selects the interstitial checkbox by default. Issue points to a problem with Vue Form Elements

https://www.dropbox.com/s/hb03duvb0f37b6x/checkbox-readonly-firstconfig.mov?dl=0

**Comment by ZLTM** [comment]
The checkbox now marks a true value when is checked and a false value when it isn't, this works correctly with the default checked property
