### ISSUE TITLE
Required If

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#724]
In this example I want to make the text box required if the toggle is selected. It doesn't work.

https://www.dropbox.com/s/uqpsyq30288bg3k/Required%20if.mov?dl=0

**Comment by caleeli** [comment]
It is because the checkbox data type is boolean, and the Required_If looks to work with only strings

**Comment by velkymx** [comment]
OK let's do the core library update, but not as part of 405, but 406

**Comment by PMQABen** [comment]
Related bug:
https://processmaker.atlassian.net/browse/FOUR-1505

**Comment by sanjacornelius** [comment]
@PMQABen  @velkymx  It looks like there an issue with validations that reference another field outside of a loop. Should this be separate ticket since it does not only affect `required_if` but also `same` and it might require some updates to the loop control?
