### ISSUE TITLE
Screen Slow

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#727]
Getting reports of screens hanging and slow with loops. Screen sent to @caleeli to investigate.

**Comment by ZLTM** [comment]
I'm still getting a slow behavior when using a nested loop
https://www.dropbox.com/s/lxzkezc5xniwptb/slow_loop.mp4?dl=0

When using a nested screen the slowness starts at the first level nested loop
when using a rich text controller the slowness starts at a third level nested loop
It looks like the slowness depends on the controller being looped, however, I think this may be an edge case, what do you think @velkymx ?
