### ISSUE TITLE
Validation Not working Referencing an outside variable

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#746]

**Comment by sanjacornelius** [comment]
Use `_parent.VARIABLE_NAME` to reference a variable outside of the loop when running validations.

https://www.loom.com/share/42bb06fd04b04d0a92c5028d2c8351d6

**Comment by velkymx** [comment]
https://github.com/ProcessMaker/screen-builder/issues/754

**Comment by PMQABen** [comment]
Yeah this is working in 4.0.6 using the steps in the video.
