### ISSUE TITLE
Rule "Required if" in loops don't work

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#754]
When assigning a"Required if" rule to a field inside a loop, the rule does not work, when the parent field is outside of the loop control.

**Comment by sanjacornelius** [comment]
This is a duplicate of this closed issue https://github.com/ProcessMaker/screen-builder/issues/746

**Comment by PMQABen** [comment]
Use `_parent.VARIABLE_NAME` to reference a variable outside of the loop when running validations.

https://www.loom.com/share/42bb06fd04b04d0a92c5028d2c8351d6
