### ISSUE TITLE
Upload Required

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#763]
Add a checkbox to the inspector for making the file upload required. 

ex:
[ ] Upload is required

Form cannot be submitted unless the file is uploaded.

**Comment by nolanpro** [comment]
Added required option in https://github.com/ProcessMaker/processmaker/pull/3232

**Comment by ZLTM** [comment]
as mentioned on https://github.com/ProcessMaker/processmaker/issues/3231 this would need to send a notification to the user in the case that a submit is sent without filling the required field
A new jira idea ticket was opened https://processmaker.atlassian.net/browse/FOUR-1687
