### ISSUE TITLE
Percentage and Validation

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#765]
The percentage validation does work as expected. 

Use case: 

I want to set the percentage requirement to be between 0-100

Current behavior:

![image](https://user-images.githubusercontent.com/535300/85302428-fdb9ec80-b45d-11ea-96d8-94fa2a59bfb1.png)

This should work

**Comment by PMQABen** [comment]
Taking away the percentage validation means it no longer validates between 0-100. I can put in 1234567890 and it will accept it. This doesn't seem like intended behavior as listed in the use case.

**Comment by PMQABen** [comment]
Validation for Between Mix/Max and data type Percentage still does not work.

**Comment by PMQABen** [comment]
Latest commit to screen builder develop branch works correctly for percentage validation.
