### ISSUE TITLE
Add support for exporting named exports for components

### ISSUE THREAD

**Issue by tdondich** [ProcessMaker/screen-builder#9]
In order to utilize this package and it's elements, it's important to export named components.

So the standalone application can be a standalone; however, using this in another project should use the exposed components.

The default export should expose a Vue plugin that can be installed to register components to Vue.

**Comment by chipit24** [comment]
Closing issue as it's over a year old without any activity, and screen builder is currently set up with named exports of the components it uses, as well as a default plugin ("install") export.
